### ISSUE TITLE
Add video links to README | Improve README/document

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahl/hacktoberfest2021#3]
This repo contains the presentation for my upcoming YouTube series on open source, there will be multiple videos o my channel https://youtube.com/TheLeanProgrammer - the idea is to improve the README to something like this - [https://github.com/MadhavBahl/slides](https://github.com/MadhavBahl/slides)

Please comment below if you want this issue to be assigned to you before start working. Help appreciated.

![image](https://user-images.githubusercontent.com/26179770/135708543-e9a6dd0c-e98a-4be8-8f31-5b652214bf60.png)

**Comment by alberturria** [comment]
Hi @MadhavBahl do you mind if I work on this? 🙂

**Comment by MadhavBahl** [comment]
I'd be happy if you do!
Assigning this to you, thanks for the help buddy ✨
